<?php

/**
 * @file
 * Provides a chuck norris entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function chuck_norris_theme() {
  return [
    'chuck_norris' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for chuck norris templates.
 *
 * Default template: chuck-norris.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the chuck norris information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_chuck_norris(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function chuck_norris_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish chuck norriss.
      $storage = \Drupal::entityTypeManager()->getStorage('chuck_norris');
      $chuck_norris_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($chuck_norris_ids) as $chuck_norris) {
        $chuck_norris->set('status', FALSE);
        $chuck_norris->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize chuck norriss.
      $storage = \Drupal::entityTypeManager()->getStorage('chuck_norris');
      $chuck_norris_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($chuck_norris_ids) as $chuck_norris) {
        $chuck_norris->setOwnerId(0);
        $chuck_norris->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function chuck_norris_user_predelete(UserInterface $account) {
  // Delete chuck norriss.
  $storage = \Drupal::entityTypeManager()->getStorage('chuck_norris');
  $chuck_norris_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $chuck_norriss = $storage->loadMultiple($chuck_norris_ids);
  $storage->delete($chuck_norriss);
}

